// reports.js

App.pages['reports'] = {
    render() {
        const container = document.createElement('div');
        container.innerHTML = `
            <div class="actions-bar glass-panel" style="padding: 1rem; border-radius: 8px; display: flex; justify-content: space-between; align-items: center;">
                <div id="inventory-status" style="display:flex; align-items:center; gap: 0.5rem">
                    <span class="status-badge status-pending">Checking Inventory Status...</span>
                </div>
                <button class="btn btn-primary" id="btn-generate-report">
                    <i class='bx bx-file'></i> Generate Inventory Report
                </button>
            </div>
            
            <div class="glass-panel table-container">
                <table id="reports-table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Report Name</th>
                            <th>Type</th>
                            <th>Generated By</th>
                            <th>Generated On</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td colspan="5" style="text-align: center;">Loading...</td></tr>
                    </tbody>
                </table>
            </div>
        `;
        return container;
    },

    async init() {
        this.checkInventoryStatus();
        this.loadReports();

        document.getElementById('btn-generate-report').addEventListener('click', () => {
            this.generateReport();
        });
    },

    async checkInventoryStatus() {
        const statusEl = document.getElementById('inventory-status');
        try {
            const data = await Api.get('/reports/status');
            
            let statusClass = 'status-active';
            if (data.status !== 'READY') statusClass = 'status-pending';

            statusEl.innerHTML = `
                <span class="status-badge ${statusClass}">Inventory: ${data.status}</span>
                <span style="font-size: 0.85rem; color: var(--gray)">${data.message || ''}</span>
            `;
        } catch (error) {
            statusEl.innerHTML = `<span class="status-badge status-inactive">Status Unavailable</span>`;
        }
    },

    async loadReports() {
        const tbody = document.querySelector('#reports-table tbody');
        try {
            const data = await Api.get('/reports/');
            
            if (!data || data.length === 0) {
                tbody.innerHTML = `<tr><td colspan="5" style="text-align: center;">No reports generated yet.</td></tr>`;
                return;
            }

            tbody.innerHTML = data.map(r => `
                <tr>
                    <td>#${r.report_id}</td>
                    <td><strong>${Utils.escapeHtml(r.report_name)}</strong></td>
                    <td><span class="badge" style="position: relative; top:0; background: var(--secondary)">${r.report_type}</span></td>
                    <td>User #${r.generated_by}</td>
                    <td>${Utils.formatDate(r.generated_on)}</td>
                </tr>
            `).join('');
            
        } catch (error) {
            tbody.innerHTML = `<tr><td colspan="5" class="text-danger" style="text-align: center;">Failed to load reports: ${error.message}</td></tr>`;
        }
    },

    async generateReport() {
        const user = Auth.getUser();
        if (!user) return;

        const payload = {
            report_name: `Inventory Snapshot - ${new Date().toLocaleDateString()}`,
            report_type: 'Inventory',
            generated_by: user.id
        };

        const btn = document.getElementById('btn-generate-report');
        btn.disabled = true;
        btn.innerHTML = `<i class='bx bx-loader-alt bx-spin'></i> Generating...`;

        try {
            const data = await Api.post('/reports/generate', payload);
            Utils.showToast(data.message, 'success');
            this.loadReports();
        } catch (error) {
            if (error.status === 423) {
                Utils.showToast("Report generation is temporarily unavailable while inventory is being updated.", "warning");
            } else {
                Utils.showToast(error.message || "Failed to generate report", "error");
            }
        } finally {
            btn.disabled = false;
            btn.innerHTML = `<i class='bx bx-file'></i> Generate Inventory Report`;
        }
    }
};
